apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 481665117634.dkr.ecr.eu-north-1.amazonaws.com/projdevops-frontend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "https://jsonplaceholder.typicode.com/todos"
        ports:
        - containerPort: 3000
